name: '${project.build.finalName}'
version: '${project.version}'
api-version: '1.20'
main: dev.paragon.quests.Core
description: Commission project for Paragon Services.
commands:
  quests:
    description: Central paragon quests command.
    aliases: [quest, q]